$repoDir = "$env:REPO_DIR"; $dvrExe = "$repoDir\chaturbate-dvr.exe"; $videosDir = "D:\videos"
$dvrLog = "$repoDir\dvr-output.log"; $tunnelUrlFile = "$repoDir\tunnel-url.txt"; $uploadFlag = "$repoDir\upload-complete.flag"
$cloudflaredPath = "$repoDir\cloudflared.exe"
$tsIp = "$env:TAILSCALE_IP"

Write-Host "========================================"
Write-Host "  RDP VIA TAILSCALE"
Write-Host "========================================"
Write-Host "Tailscale IP: $tsIp"; $null = [System.Console]::Out.Flush()
# The RDP user's password is randomly generated by the RDP-setup job
# and written to $env:TEMP\_rdppass on this runner. Surface THAT
# (don't rely on the RDP_PASSWORD secret, which is unrelated/empty).
$rdpPass = Get-Content "$env:TEMP\_rdppass" -ErrorAction SilentlyContinue
if (-not $rdpPass) { $rdpPass = $env:RDP_PASSWORD }
Write-Host "Username: RDP"
Write-Host "Password: $rdpPass"
Write-Host "mstsc /v:$tsIp"

Set-Location $repoDir
$env:TEMP = "D:\temp"; $env:TMP = "D:\temp"; $env:TMPDIR = "D:\temp"
New-Item -ItemType Directory -Force -Path "D:\temp" | Out-Null
Write-Host ("(DISK) C: free=" + [math]::Round((Get-PSDrive C).Free/1GB,1) + "GB  D: free=" + [math]::Round((Get-PSDrive D).Free/1GB,1) + "GB")

# ---- Background C-drive cleaner (single hidden run) --------------------------
# Launches scripts/clean-c.ps1 once in a hidden window so C: stale temp files and
# the Recycle Bin are cleaned without blocking the keep-alive loop. It only
# targets safe C: temp/cache dirs (never Program Files, chocolatey, Tailscale,
# D:\temp, D:\repos, D:\videos) and skips anything recent/in use. Logs to D:\temp.
$cleanScript = Join-Path $repoDir "scripts\clean-c.ps1"
if (Test-Path $cleanScript) {
  $cleanSh = if (Get-Command pwsh -ErrorAction SilentlyContinue) { "pwsh" } else { "powershell" }
  $cleanLog = "D:\temp\clean-c.log"
  $cleanProc = Start-Process -FilePath $cleanSh -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$cleanScript`"" -WindowStyle Hidden -RedirectStandardOutput $cleanLog -RedirectStandardError "D:\temp\clean-c.err.log" -PassThru
  Write-Host "(CLEAN) background C-drive cleaner started (pid $($cleanProc.Id), single run -> $cleanLog)"; $null = [System.Console]::Out.Flush()
} else {
  Write-Host "(CLEAN) clean-c.ps1 not found at $cleanScript"
}

Remove-Item Env:HTTP_PROXY,Env:HTTPS_PROXY,Env:http_proxy,Env:https_proxy -ErrorAction SilentlyContinue
# SESSION_DURATION, VIDHIDE_API_KEY, STREAMWISH_API_KEY, UPNSHARE_KEY, etc.
# are passed via the step's env: block from GitHub secrets — $env:XXX works directly.
$dvr = Start-Process -FilePath $dvrExe -ArgumentList "--no-tunnel --output-dir `"$videosDir`"" -WorkingDirectory $repoDir -NoNewWindow -RedirectStandardOutput $dvrLog -RedirectStandardError "$repoDir\dvr-err.log" -PassThru
$dvrPid = if ($dvr -and $dvr.Id) { $dvr.Id } else { "?" }


$tunnelUrl = $null; $tun = $null; $tunnelJob = $null; $lastWebUrlUpdate = $null
$turlTemp = "D:\temp\_turl"
if (Test-Path $cloudflaredPath) {
  $stderr = "$repoDir\tunnel-stderr.log"
  $tun = Start-Process -FilePath $cloudflaredPath -ArgumentList "tunnel --url http://localhost:8080 --protocol http2" -WorkingDirectory $repoDir -NoNewWindow -RedirectStandardError $stderr -PassThru
  if ($tun) { $tunnelJob = Start-Job -ScriptBlock { param($f,$o) for ($i = 0; $i -lt 50; $i++) { if ($i -gt 0 -and $i % 10 -eq 0) { Write-Host ('[TUNNEL] Waiting for cloudflared... attempt ' + $i + '/50') }; Start-Sleep -Seconds 2; if (Test-Path $f) { $c = Get-Content $f -Raw; $m = [regex]::Match($c, 'https://(?!api\.)[a-z0-9\-]+\.trycloudflare\.com'); if ($m.Success) { Write-Host ('[TUNNEL] Found URL at attempt ' + $i + '/50'); $m.Value | Set-Content $o -Force; return $m.Value } } }; Write-Host '[TUNNEL] Timeout after 50 attempts — will retry in main loop'; return $null } -ArgumentList $stderr,$turlTemp }
}

if ($dvrPid -ne "?") { Write-Host "(OK) DVR PID: $dvrPid" }
for ($i = 0; $i -lt 60; $i++) {
  if (-not $dvr) { break }
  if ($dvr.HasExited) {
    Write-Host "(ERROR) DVR exited (code: $($dvr.ExitCode))"
    Write-Host "--- DVR stdout tail ---"; Get-Content $dvrLog -Tail 15 -ErrorAction SilentlyContinue
    Write-Host "--- DVR stderr tail ---"; Get-Content "$repoDir\dvr-err.log" -Tail 15 -ErrorAction SilentlyContinue
    break
  }
  if (Get-NetTCPConnection -LocalPort 8080 -State Listen -ErrorAction SilentlyContinue) { break }
  Start-Sleep -Seconds 3
}
Write-Host "(OK) DVR on port 8080"



if ($tunnelJob) { $null = $tunnelJob | Wait-Job -Timeout 30 -ErrorAction SilentlyContinue; $tunnelUrl = Receive-Job $tunnelJob -ErrorAction SilentlyContinue; Remove-Job $tunnelJob -Force -ErrorAction SilentlyContinue }
if (-not $tunnelUrl -and (Test-Path $turlTemp)) { $tunnelUrl = (Get-Content $turlTemp -Raw).Trim() }
function Shorten-Url {
  param($u)
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  $enc = [uri]::EscapeDataString($u)
  try { $r = Invoke-RestMethod -Uri "https://tinyurl.com/api-create.php?url=$enc" -TimeoutSec 15 -ErrorAction Stop; if ($r) { return "$r" } } catch {}
  try { $r = Invoke-RestMethod -Uri ('https://is.gd/create.php?format=simple&url=' + $enc) -TimeoutSec 15 -ErrorAction Stop; if ($r) { return "$r" } } catch {}
  try { $r = Invoke-RestMethod -Uri ('https://v.gd/create.php?format=simple&url=' + $enc) -TimeoutSec 15 -ErrorAction Stop; if ($r) { return "$r" } } catch {}
  try { $r = Invoke-RestMethod -Uri "https://clck.ru/--?url=$enc" -TimeoutSec 15 -ErrorAction Stop; if ($r) { return "$r" } } catch {}
  return $null
}
function Get-NodeId {
  if (-not [string]::IsNullOrWhiteSpace($env:NODE_ID)) { return $env:NODE_ID }
  if (-not [string]::IsNullOrWhiteSpace($env:GITHUB_REPOSITORY)) {
    $parts = $env:GITHUB_REPOSITORY -split '/'
    if ($parts.Count -ge 2) { return $parts[1] }
  }
  return $null
}
function Update-NodeWebUrl {
  param($nodeId, $url)
  if ([string]::IsNullOrWhiteSpace($nodeId)) { Write-Warning "(WARN) nodeId is empty - skipping web_url update"; return }
  # Resolve Supabase credentials. Prefer the runner env (GitHub secrets),
  # then fall back to the .env file written earlier in the pipeline.
  $sbUrl = if (-not [string]::IsNullOrWhiteSpace($env:SUPABASE_URL)) { $env:SUPABASE_URL.Trim() } else { $null }
  $sbKey = if (-not [string]::IsNullOrWhiteSpace($env:SUPABASE_API_KEY)) { $env:SUPABASE_API_KEY.Trim() } else { $null }
  if (-not $sbUrl -or -not $sbKey) {
    $sb = Get-Content "$repoDir\.env" -Raw -ErrorAction SilentlyContinue
    if ($sb) {
      if (-not $sbUrl -and ($sb -match '(?m)^SUPABASE_URL=(.+)$')) { $sbUrl = $matches[1].Trim() }
      if (-not $sbKey -and ($sb -match '(?m)^SUPABASE_API_KEY=(.+)$')) { $sbKey = $matches[1].Trim() }
    }
  }
  # Guard against placeholder/junk secret values (e.g. a single '-') that
  # slipped into the env - fall back to the .env file's real value.
  if ($sbUrl -and ($sbUrl -match '^\-+$' -or $sbUrl.Trim().Length -le 2)) {
    Write-Warning "(WARN) SUPABASE_URL env value looks like a placeholder ('$sbUrl') - falling back to .env"
    $sb = Get-Content "$repoDir\.env" -Raw -ErrorAction SilentlyContinue
    $sbUrl = $null; $sbKey = $null
    if ($sb) {
      if ($sb -match '(?m)^SUPABASE_URL=(.+)$') { $sbUrl = $matches[1].Trim() }
      if ($sb -match '(?m)^SUPABASE_API_KEY=(.+)$') { $sbKey = $matches[1].Trim() }
    }
  }
  if ([string]::IsNullOrWhiteSpace($sbUrl)) { Write-Warning "(WARN) SUPABASE_URL missing (no secret, no .env) - cannot update web_url"; return }
  if ([string]::IsNullOrWhiteSpace($sbKey)) { Write-Warning "(WARN) SUPABASE_API_KEY missing (no secret, no .env) - cannot update web_url"; return }
  if ($sbUrl -notmatch '^https?://') { $sbUrl = 'https://' + $sbUrl }
  $sbUrl = $sbUrl.TrimEnd('/')
  # UPSERT the node row (POST + on_conflict=node_id) so web_url lands even if the
  # Go DVR (which only self-registers in coordinator mode) hasn't created the row
  # yet. A PATCH on a non-existent row is a silent no-op (HTTP 200, 0 rows updated).
  $instanceLabel = if (-not [string]::IsNullOrWhiteSpace($env:INSTANCE_LABEL)) { $env:INSTANCE_LABEL } else { $env:GITHUB_RUN_ID }
  $payload = @{
    node_id        = $nodeId
    web_url        = $url
    status         = "online"
    hostname       = $env:COMPUTERNAME
    instance_label = $instanceLabel
    current_load   = 0
  }
  $body = $payload | ConvertTo-Json -Compress
  $apiUrl = "$sbUrl/rest/v1/nodes?on_conflict=node_id"
  # Force TLS 1.2 (the default protocol on the runner causes
  # "The underlying connection was closed" against Supabase).
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  # Supabase is fronted by Cloudflare, which resets the .NET Framework TLS
  # handshake that Invoke-RestMethod sends (the Go DVR client and curl.exe both
  # pass). Prefer curl.exe direct (--noproxy "*"), fall back to Invoke-RestMethod.
  $ok = $false
  $sbHost = ([uri]$sbUrl).Host
  $sbPort = ([uri]$sbUrl).Port
  if ($sbPort -eq -1 -or -not $sbPort) { $sbPort = 443 }
  # Hex-encoded host is NOT masked by GitHub log redaction (plaintext is), so
  # this shows the exact host the runner is using for Supabase.
  Write-Host "(DBG) Supabase host: '$sbHost' (hex: $([BitConverter]::ToString([Text.Encoding]::UTF8.GetBytes($sbHost)).Replace('-','')))"

  # Pre-flight DNS + TCP check to distinguish "project paused / network blocked"
  # from an auth/transport error. Run once, before the retry loop.
  $tcpProbeOk = $true
  try { $null = [Net.Dns]::GetHostEntry($sbHost) } catch {
    Write-Warning "(WARN) Supabase DNS resolution failed for $sbHost — check SUPABASE_URL"
  }
  $tcp = New-Object Net.Sockets.TcpClient
  try {
    $conn = $tcp.BeginConnect($sbHost, $sbPort, $null, $null)
    if ($conn.AsyncWaitHandle.WaitOne(5000, $false)) {
      try { $tcp.EndConnect($conn) | Out-Null } catch { Write-Warning "(WARN) Supabase TCP connect failed: $($_.Exception.InnerException.Message)" }
    } else {
      $tcpProbeOk = $false
      Write-Warning "(WARN) Supabase TCP connect timeout ($sbHost`:$sbPort) - project may be paused, IP blocked, or network unreachable"
    }
  } finally {
    $tcp.Close()
  }

  # Preflight is informational only: curl with DoH can succeed even when the OS
  # resolver NXDOMAINs the host, so always attempt the upsert.
  if ($true) {
    for ($attempt = 1; $attempt -le 3; $attempt++) {
      $code = "000"
      try {
        $curlOut = & "curl.exe" -s -o NUL -w "%{http_code}" -X POST $apiUrl -H "apikey: $sbKey" -H "Authorization: Bearer $sbKey" -H "Content-Type: application/json" -H "Prefer: resolution=merge-duplicates" -d $body --noproxy "*" --tlsv1.2 --doh-url "https://cloudflare-dns.com/dns-query" -m 20 2>&1
        $code = "$curlOut".Trim()
      } catch {
        Write-Warning "(WARN) web_url curl attempt $attempt failed: $_"
      }
      if ($code -match '^(2\d\d)$') {
        Write-Host "(OK) Upserted node $nodeId web_url via curl.exe (attempt $attempt, HTTP $code)"
        $ok = $true; break
      }
      Write-Warning "(WARN) web_url curl attempt $attempt returned HTTP $code"
      if ($attempt -lt 3) { Start-Sleep -Seconds 5 }
    }
  }

  if (-not $ok) {
    # Fallback: Invoke-RestMethod. Clear ALL_PROXY for the call; restore after.
    try {
      $savedAllProxy = $env:ALL_PROXY
      Remove-Item Env:ALL_PROXY -ErrorAction SilentlyContinue
      Remove-Item Env:all_proxy -ErrorAction SilentlyContinue
      Invoke-RestMethod -Uri $apiUrl -Method Post -Body $body -ContentType "application/json" -Headers @{ "apikey" = $sbKey; "Authorization" = "Bearer $sbKey"; "Prefer" = "resolution=merge-duplicates" } -TimeoutSec 25 -ErrorAction Stop | Out-Null
      Write-Host "(OK) Upserted node $nodeId web_url via Invoke-RestMethod"
      $ok = $true
    } catch {
      $errMsg = $_.Exception.Message
      $innerMsg = if ($_.Exception.InnerException) { $_.Exception.InnerException.Message } else { "" }
      $diag = if ($innerMsg -and $innerMsg -ne $errMsg) { "$errMsg [$innerMsg]" } else { $errMsg }
      Write-Warning "(WARN) Invoke-RestMethod web_url update failed: $diag"
    } finally {
      if ($savedAllProxy) { $env:ALL_PROXY = $savedAllProxy }
    }
  }
  if (-not $ok) { Write-Warning "(WARN) Failed to update web_url after all attempts" }
}
$myNodeId = Get-NodeId
Write-Host "(OK) Node ID: $myNodeId"; $null = [System.Console]::Out.Flush()
$cachedShortUrl = $null; $lastTunnelUrl = $null; $shortUrlJob = $null

# Enable Tailscale Funnel in background (can hang, so timeout via job)
$funnelUrl = $null
$tsExe = "$env:ProgramFiles\Tailscale\tailscale.exe"
if (Test-Path $tsExe) {
  $funnelJob = Start-Job -ScriptBlock {
    param($exe)
    & $exe funnel 8080 2>&1 | Out-Null
    $fs = & $exe funnel status 2>&1 | Out-String
    if ($fs -match 'https://[a-z0-9\-]+\.[a-z0-9\-]+\.ts\.net') { return $matches[0].Trim() }
    return $null
  } -ArgumentList $tsExe
  $null = $funnelJob | Wait-Job -Timeout 15 -ErrorAction SilentlyContinue
  $funnelUrl = Receive-Job $funnelJob -ErrorAction SilentlyContinue
  Remove-Job $funnelJob -Force -ErrorAction SilentlyContinue
  if ($funnelUrl) { Write-Host "(OK) Tailscale Funnel: $funnelUrl" }
}

# Retry tunnel URL extraction from stderr log (cloudflared may still be starting)
if (-not $tunnelUrl -and $tun -and (-not $tun.HasExited)) {
  $stderr = "$repoDir\tunnel-stderr.log"
  for ($i = 0; $i -lt 45; $i++) {
    if ($i -gt 0 -and $i % 10 -eq 0) { Write-Host "[TUNNEL] Post-DVR retry $i/45..."; $null = [System.Console]::Out.Flush() }
    Start-Sleep -Seconds 2
    if (Test-Path $stderr) { $c = Get-Content $stderr -Raw; $m = [regex]::Match($c, 'https://(?!api\.)[a-z0-9\-]+\.trycloudflare\.com'); if ($m.Success) { Write-Host "[TUNNEL] Found URL at post-DVR retry $i/45"; $tunnelUrl = $m.Value; break } }
    if ($tun.HasExited) { Write-Host "[TUNNEL] cloudflared exited during post-DVR retry at attempt $i/45"; break }
  }
  if (-not $tunnelUrl) { Write-Host "[TUNNEL] Post-DVR retry exhausted (45×2s) — will retry in main loop" }
}

if ($tunnelUrl -and $myNodeId) {
  $tunnelUrl | Set-Content $tunnelUrlFile -Force
  $lastTunnelUrl = $tunnelUrl
  Write-Host "(OK) Tunnel URL: $tunnelUrl"; $null = [System.Console]::Out.Flush()
  $sb = { param($u) $enc = [uri]::EscapeDataString($u); try { $r = Invoke-RestMethod -Uri "https://tinyurl.com/api-create.php?url=$enc" -TimeoutSec 10 -ErrorAction Stop; if ($r) { return "$r" } } catch {}; try { $r = Invoke-RestMethod -Uri ('https://is.gd/create.php?format=simple&url=' + $enc) -TimeoutSec 10 -ErrorAction Stop; if ($r) { return "$r" } } catch {}; return $null }
  $shortUrlJob = Start-Job -ScriptBlock $sb -ArgumentList $tunnelUrl
  Update-NodeWebUrl $myNodeId "$tunnelUrl"
} elseif ($funnelUrl -and $myNodeId) {
  Write-Host "(OK) Using Tailscale Funnel: $funnelUrl"; $null = [System.Console]::Out.Flush()
  $lastTunnelUrl = $funnelUrl
  Update-NodeWebUrl $myNodeId "$funnelUrl"
} else {
  Write-Host "(WARN) No tunnel URL available yet — will keep retrying"; $null = [System.Console]::Out.Flush()
}

# Poll background short URL job once
if ($shortUrlJob) {
  $null = $shortUrlJob | Wait-Job -Timeout 10 -ErrorAction SilentlyContinue
  $cachedShortUrl = Receive-Job $shortUrlJob -ErrorAction SilentlyContinue
  Remove-Job $shortUrlJob -Force -ErrorAction SilentlyContinue
  if ($cachedShortUrl) {
    Write-Host "(OK) Dashboard: $cachedShortUrl"
    $null = [System.Console]::Out.Flush()
    if ($env:GITHUB_STEP_SUMMARY) {
      "## Dashboard" | Out-File $env:GITHUB_STEP_SUMMARY -Encoding utf8
      "Open your RDP dashboard: [$cachedShortUrl]($cachedShortUrl)" | Out-File $env:GITHUB_STEP_SUMMARY -Encoding utf8 -Append
    }
  }
}

Remove-Item $uploadFlag -Force -ErrorAction SilentlyContinue
$startTime = if ($env:START_TIME) { [int64]$env:START_TIME } else { [DateTimeOffset]::UtcNow.ToUnixTimeSeconds() }
$targetDuration = 355 * 60

$lastNotifyTime = 0
$notifyCooldown = 300

function Send-Notify {
  param($level, $msg)
  $wh = [Environment]::GetEnvironmentVariable("DISCORD_WEBHOOK")
  if ([string]::IsNullOrWhiteSpace($wh)) { return }
  $now = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
  if ($now - $script:lastNotifyTime -lt $script:notifyCooldown) { return }
  $script:lastNotifyTime = $now
  $colors = @{ info = 3447003; warn = 16776960; error = 15548997; critical = 15548997 }
  $body = @{ embeds = @(@{ title = "[$level] $env:GITHUB_REPOSITORY"; description = $msg; color = $colors[$level]; timestamp = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ") }) } | ConvertTo-Json -Depth 5 -Compress
  try { Invoke-RestMethod -Uri $wh -Method Post -Body $body -ContentType "application/json" -TimeoutSec 10 -ErrorAction Stop | Out-Null } catch {}
}

# ── Main keep-alive loop ─────────────────────────────────
while ($true) {
  $now = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds(); $elapsed = $now - $startTime
  if ($elapsed -ge $targetDuration) { break }
  $sleepSecs = [Math]::Min($targetDuration - $elapsed, 60)
  if ($sleepSecs -le 0) { break }

  # ═══ DVR health ═══
  if (-not $dvr) { Write-Warning "(WARN) DVR process not available"; continue }
  if ($dvr.HasExited) {
    Write-Host "(WARN) DVR exited (code: $($dvr.ExitCode)) - restarting..."
    $lastLogs = Get-Content "$repoDir\dvr-err.log" -Tail 10 -ErrorAction SilentlyContinue
    Send-Notify "error" "DVR exited code $($dvr.ExitCode)`nLast stderr: $($lastLogs -join "`n")"
    $null = [System.Console]::Out.Flush()
    $env:SESSION_DURATION = "$([Math]::Max(1, [math]::Floor((5*3600+20*60 - $elapsed)/60)))m0s"
    $dvr = Start-Process -FilePath $dvrExe -ArgumentList "--no-tunnel --output-dir `"$videosDir`"" -WorkingDirectory $repoDir -NoNewWindow -RedirectStandardOutput $dvrLog -RedirectStandardError "$repoDir\dvr-err.log" -PassThru
  }






  if (-not $tunnelUrl) {
    if (-not $tunnelRetryCount) { $tunnelRetryCount = 0 }; $tunnelRetryCount++
    if ($tunnelRetryCount % 5 -eq 0) { Write-Host "[TUNNEL] Main-loop retry #$tunnelRetryCount — still waiting for cloudflared tunnel URL"; $null = [System.Console]::Out.Flush() }
    $stderr = "$repoDir\tunnel-stderr.log"
    if (Test-Path $stderr) {
      $c = Get-Content $stderr -Raw
      $m = [regex]::Match($c, 'https://(?!api\.)[a-z0-9\-]+\.trycloudflare\.com')
      if ($m.Success) {
        $tunnelUrl = $m.Value
        $tunnelUrl | Set-Content $tunnelUrlFile -Force
        $lastTunnelUrl = $tunnelUrl
        Write-Host "(OK) Tunnel URL found on main-loop retry #${tunnelRetryCount}: $tunnelUrl"
        $null = [System.Console]::Out.Flush()
        $sb = { param($u) $enc = [uri]::EscapeDataString($u); try { $r = Invoke-RestMethod -Uri "https://tinyurl.com/api-create.php?url=$enc" -TimeoutSec 10 -ErrorAction Stop; if ($r) { return "$r" } } catch {}; try { $r = Invoke-RestMethod -Uri ('https://is.gd/create.php?format=simple&url=' + $enc) -TimeoutSec 10 -ErrorAction Stop; if ($r) { return "$r" } } catch {}; return $null }
        $shortUrlJob = Start-Job -ScriptBlock $sb -ArgumentList $tunnelUrl
        Update-NodeWebUrl $myNodeId "$tunnelUrl"
      }
    }
    if ((Test-Path $cloudflaredPath) -and ((-not $tun -or $tun.HasExited) -or $tunnelRetryCount -ge 10)) {
      if ($tunnelRetryCount -ge 10 -and $tun -and (-not $tun.HasExited)) {
        Write-Host "[TUNNEL] Force-restarting cloudflared (stuck after $tunnelRetryCount retries)..."
        $null = [System.Console]::Out.Flush(); $tun.Kill() | Out-Null; Start-Sleep -Seconds 3
      } elseif (-not $tun -or $tun.HasExited) {
        Write-Host "(WARN) Tunnel not running - restarting cloudflared..."
        $null = [System.Console]::Out.Flush()
      }
      if (Test-Path $stderr) { Remove-Item $stderr -Force }
      $tun = Start-Process -FilePath $cloudflaredPath -ArgumentList "tunnel --url http://localhost:8080 --protocol http2" -WorkingDirectory $repoDir -NoNewWindow -RedirectStandardError $stderr -PassThru
      Start-Sleep -Seconds 10; $tunnelRetryCount = 0
    }
  }

  # ═══ Short URL job poll ═══
  if ($shortUrlJob -and ($shortUrlJob.State -eq 'Completed')) {
    $cachedShortUrl = Receive-Job $shortUrlJob -ErrorAction SilentlyContinue
    Remove-Job $shortUrlJob -Force -ErrorAction SilentlyContinue; $shortUrlJob = $null
    if ($cachedShortUrl) {
      Write-Host "(OK) Dashboard: $cachedShortUrl"
      $null = [System.Console]::Out.Flush()
      if ($env:GITHUB_STEP_SUMMARY) {
        "## Dashboard" | Out-File $env:GITHUB_STEP_SUMMARY -Encoding utf8
        "Open your RDP dashboard: [$cachedShortUrl]($cachedShortUrl)" | Out-File $env:GITHUB_STEP_SUMMARY -Encoding utf8 -Append
      }
    }
  }

  # ═══ Tunnel process restart ═══
  if ($tun -and $tun.HasExited) {
    Write-Host "(WARN) Tunnel exited - restarting..."
    $null = [System.Console]::Out.Flush()
    $stderr = "$repoDir\tunnel-stderr.log"
    if (Test-Path $stderr) { Remove-Item $stderr -Force }
    $tun = Start-Process -FilePath $cloudflaredPath -ArgumentList "tunnel --url http://localhost:8080 --protocol http2" -WorkingDirectory $repoDir -NoNewWindow -RedirectStandardError $stderr -PassThru
    Start-Sleep -Seconds 10
  }

  # ═══ Status output ═══
  if ($cachedShortUrl) { $pub = " | $cachedShortUrl" }
  elseif ($tunnelUrl) { $pub = " | $tunnelUrl" }
  elseif ($funnelUrl) { $pub = " | $funnelUrl" }
  else { $pub = "" }
  $now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
  Write-Host "[$now] $tsIp$pub (Elapsed: $([Math]::Round($elapsed/60,1))m)"; $null = [System.Console]::Out.Flush()

  # ═══ Periodic web_url refresh (every 5 min) ═══
  if ($tunnelUrl -and $myNodeId) {
    if (-not $lastWebUrlUpdate) { $lastWebUrlUpdate = 0 }
    if ($elapsed - $lastWebUrlUpdate -ge 300) {
      $lastWebUrlUpdate = $elapsed
      Update-NodeWebUrl $myNodeId "$tunnelUrl"
    }
  }

  Start-Sleep -Seconds $sleepSecs
}
$waitStart = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
while (-not (Test-Path $uploadFlag) -and ([DateTimeOffset]::UtcNow.ToUnixTimeSeconds() - $waitStart) -lt 240) { Start-Sleep -Seconds 15 }
if (Test-Path $uploadFlag) { Remove-Item $uploadFlag -Force }

gh workflow run secure-rdp.yml --repo $env:GITHUB_REPOSITORY --ref $env:GITHUB_REF_NAME
